### ISSUE TITLE
Include/Link processing script used to generate those CSV files and document in README

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/data_normalize_metric_pam50#1]

**Comment by sandrinebedard** [comment]
https://github.com/sct-pipeline/dcm-metric-normalization/blob/main/scripts/process_data_spine-generic.sh

**Comment by sandrinebedard** [comment]
Wait for updated version fo the script using the final version with sct_process_segmentation

**Comment by valosekj** [comment]
I created a [release](https://github.com/sct-pipeline/dcm-metric-normalization/releases/tag/r20230221) of `dcm-metric-normalization` repo.

The script I used to generate the CSV files:
https://github.com/sct-pipeline/dcm-metric-normalization/blob/r20230221/scripts/process_data_spine-generic.sh

**Comment by valosekj** [comment]
The script added to README in https://github.com/spinalcordtoolbox/data_normalize_metric_pam50/commit/f35a55e7bacacb38ad244cff454b7598c7e3fbfe --> closing this issue
